# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appconfigguard < Formula
  desc "A Go-based CLI tool for safely managing Azure App Configuration"
  homepage "https://github.com/chan27-2/appconfigguard"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/chan27-2/appconfigguard/releases/download/v0.1.2/appconfigguard_Darwin_x86_64.tar.gz"
      sha256 "e231b7eb91220f3cb2e28b769939fe9f799325ad924e77887695c810608705af"

      def install
        bin.install "appconfigguard"
      end
    end
    on_arm do
      url "https://github.com/chan27-2/appconfigguard/releases/download/v0.1.2/appconfigguard_Darwin_arm64.tar.gz"
      sha256 "588a1994074b70d29539d09a2914a04da9e63e15f6e9b72e512f9257a36c755e"

      def install
        bin.install "appconfigguard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chan27-2/appconfigguard/releases/download/v0.1.2/appconfigguard_Linux_x86_64.tar.gz"
        sha256 "d86e6eb33ce081745c5472f80828d09853ef66fc02695a3c86426c622e696c74"

        def install
          bin.install "appconfigguard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chan27-2/appconfigguard/releases/download/v0.1.2/appconfigguard_Linux_arm64.tar.gz"
        sha256 "4f8f1c447aef6888bfe589cc3d6e63dd0ce0b0da2be3acdd0f1f1f17c39ccee5"

        def install
          bin.install "appconfigguard"
        end
      end
    end
  end

  test do
    system "#{bin}/appconfigguard --version"
  end
end
